FROM python:3.12

RUN apt-get update && apt-get install -y \
    && rm -rf /var/lib/apt/lists/*

RUN pip install kafka-python pandas

WORKDIR /app

COPY generate_sample_data.py .
COPY data/sample_orders.csv ./data/

CMD ["python", "generate_sample_data.py"]