FROM python:3.12-slim

WORKDIR /app

# Instala dependências do confluent-kafka
RUN apt-get update && apt-get install -y --no-install-recommends \
        gcc \
        librdkafka-dev \
    && rm -rf /var/lib/apt/lists/*

COPY src/ingestion/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ingestion/ /app

CMD ["python", "generate_sample_data.py"]
