name: lakehouse_dbt
version: '1.0'
profile: lakehouse_dbt

model-paths: ["models"]

seed-paths: ["data"]

target-path: "target"
clean-targets: ["target"]

models:
  lakehouse_dbt:
    +materialized: table

seeds:
  lakehouse_dbt:
    +schema: raw
